
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqwtihrinxprrgdwhmua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxd3RpaHJpbnhwcnJnZHdobXVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjIyMTMsImV4cCI6MjA2MDg5ODIxM30.oztPKRVpxqL4wkTZ7pdmZ9lqP47LGQs5V_T76LbuCzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
